### ISSUE TITLE
Recommend implementing components according to the PSR specification

### ISSUE THREAD

**Issue by alphasnow** [hunzhiwange/framework#132]
I recommend implementing components according to the PSR specification.
Because the PSR specification can make the components more versatile.

> https://www.php-fig.org/psr/psr-3/

**Comment by doyouhaobaby** [comment]
日志用的monolog,http用的symfony的，大部分还是遵循PSR标准，有一些确实没有弄，考虑看看。

**Comment by alphasnow** [comment]
类似 `Leevel\Log\ILog` 接口可以使用 `Psr\Log\LoggerInterface` 替换, 使用到扩展包`psr/log`,
其他比较常用还有 `psr/simple-cache`, `psr/container`

**Comment by doyouhaobaby** [comment]
> 类似 `Leevel\Log\ILog` 接口可以使用 `Psr\Log\LoggerInterface` 替换, 使用到扩展包`psr/log`, 其他比较常用还有 `psr/simple-cache`, `psr/container`

确实，最近太忙了，后面一段时间腾出精力了来改改看

**Comment by doyouhaobaby** [comment]
> 类似 `Leevel\Log\ILog` 接口可以使用 `Psr\Log\LoggerInterface` 替换, 使用到扩展包`psr/log`, 其他比较常用还有 `psr/simple-cache`, `psr/container`

将日志重构掉了
